# Generated by Django 3.2.5 on 2021-07-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/no-image.jpg', upload_to='images/'),
        ),
    ]
